name: Deployment pipeline

on:
  push:
      branches:
          - main
  pull_request:
      branches: [main]
      types: [opened, synchronize]

permissions:
  contents: write

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Check style
        run: npm run eslint
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Intentional Fail (remove after testing)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: exit 1
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Deploy (Render)
        id: deploy
        if: >-
          ${{ github.event_name == 'push' &&
              !contains(toJson(github.event), '#skip') }}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
      - name: Discord webhook (deploy)
        if: ${{ steps.deploy.outcome == 'success' }}
        uses: hunghg255/action-notifications@master
        with:
          description: Commit [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}) deployed to production.
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Discord webhook (failure)
        if: ${{ always() && steps.deploy.outcome == 'failure' }}
        uses: hunghg255/action-notifications@master
        with:
          description: Deployment of commit [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}) failed.
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        if: >-
          ${{ github.event_name == 'push' &&
              !contains(toJson(github.event), '#skip') }}
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      